### ISSUE TITLE
加载lib.so提示报错，找不到文件

### ISSUE THREAD

**Issue by Jucyfer** [ktrader-tech/jctp#2]
org.scijava.nativelib.BaseJniExtractor取得临时路径并解压完三个lib之后，org.scijava.nativelib.NativeLibraryUtil报错如下：

java.lang.UnsatisfiedLinkError:/tmp/nativelib-loader_4608108371900239056/libjctp.so: libthostmduserapi_se.so: 无法打开共享对象文件: 没有那个文件或目录

但是ls这个目录，却可以看到已解压的文件。请问是否需要做额外变量路径的配置？

如果手工将这两个lib拖放到固定的目录下，并添加LD_LIBRARY_PATH之后，问题就消失了

测试环境为idea，用maven引入。

谢谢！

**Comment by Jucyfer** [comment]
贴上完整的日志与堆栈：
08:14:24.501 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - processor is INTEL_64 os.arch is amd64
08:14:24.504 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
08:14:24.504 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
08:14:24.504 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/linux_64/
08:14:24.504 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libthostmduserapi_se.so
08:14:24.505 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - URL is jar:file:/home/j***r/.m2/repository/org/rationalityfrontline/jctp/6.6.1_P1-1.0.3/jctp-6.6.1_P1-1.0.3.jar!/natives/linux_64/libthostmduserapi_se.so
08:14:24.505 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - URL path is file:/home/j***r/.m2/repository/org/rationalityfrontline/jctp/6.6.1_P1-1.0.3/jctp-6.6.1_P1-1.0.3.jar!/natives/linux_64/libthostmduserapi_se.so
08:14:24.507 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/home/j***r/.m2/repository/org/rationalityfrontline/jctp/6.6.1_P1-1.0.3/jctp-6.6.1_P1-1.0.3.jar!/natives/linux_64/libthostmduserapi_se.so' to '/tmp/nativelib-loader_4608108371900239056/libthostmduserapi_se.so'
08:15:02.344 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
08:15:02.344 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/linux_64/
08:15:02.344 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libthosttraderapi_se.so
08:15:02.345 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - URL is jar:file:/home/j***r/.m2/repository/org/rationalityfrontline/jctp/6.6.1_P1-1.0.3/jctp-6.6.1_P1-1.0.3.jar!/natives/linux_64/libthosttraderapi_se.so
08:15:02.345 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - URL path is file:/home/j***r/.m2/repository/org/rationalityfrontline/jctp/6.6.1_P1-1.0.3/jctp-6.6.1_P1-1.0.3.jar!/natives/linux_64/libthosttraderapi_se.so
08:15:02.345 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/home/j***r/.m2/repository/org/rationalityfrontline/jctp/6.6.1_P1-1.0.3/jctp-6.6.1_P1-1.0.3.jar!/natives/linux_64/libthosttraderapi_se.so' to '/tmp/nativelib-loader_4608108371900239056/libthosttraderapi_se.so'
08:15:02.368 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
08:15:02.368 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/linux_64/
08:15:02.368 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libjctp.so
08:15:02.368 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - URL is jar:file:/home/j***r/.m2/repository/org/rationalityfrontline/jctp/6.6.1_P1-1.0.3/jctp-6.6.1_P1-1.0.3.jar!/natives/linux_64/libjctp.so
08:15:02.368 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - URL path is file:/home/j***r/.m2/repository/org/rationalityfrontline/jctp/6.6.1_P1-1.0.3/jctp-6.6.1_P1-1.0.3.jar!/natives/linux_64/libjctp.so
08:15:02.369 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/home/j***r/.m2/repository/org/rationalityfrontline/jctp/6.6.1_P1-1.0.3/jctp-6.6.1_P1-1.0.3.jar!/natives/linux_64/libjctp.so' to '/tmp/nativelib-loader_4608108371900239056/libjctp.so'

08:15:17.605 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - Problem with library
java.lang.UnsatisfiedLinkError: /tmp/nativelib-loader_4608108371900239056/libjctp.so: libthostmduserapi_se.so: 无法打开共享对象文件: 没有那个文件或目录
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:767)
	at java.base/java.lang.System.load(System.java:1831)
	at org.scijava.nativelib.NativeLibraryUtil.loadNativeLibrary(NativeLibraryUtil.java:353)
	at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:139)
	at org.rationalityfrontline.jctp.jctpJNI.<clinit>(jctpJNI.java:29)
	at org.rationalityfrontline.jctp.CThostFtdcMdApi.CreateFtdcMdApi(CThostFtdcMdApi.java:45)
        at cc..test.prototype.stuff.Stuff20220227.main(Stuff20220227.java:69)
Failed to load CTP native library: 
java.io.IOException: Couldn't load library library jctp
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.rationalityfrontline.jctp.jctpJNI.CThostFtdcMdApi_CreateFtdcMdApi__SWIG_2(Ljava/lang/String;)J
	at org.rationalityfrontline.jctp.jctpJNI.CThostFtdcMdApi_CreateFtdcMdApi__SWIG_2(Native Method)
	at org.rationalityfrontline.jctp.CThostFtdcMdApi.CreateFtdcMdApi(CThostFtdcMdApi.java:45)
	at cc..test.prototype.stuff.Stuff20220227.main(Stuff20220227.java:69)

**Comment by Jucyfer** [comment]
@RationalityFrontline

**Comment by Jucyfer** [comment]
继续深挖发现，在加载jctp.so时，ClassLoader的usr_paths并没有包含/tmp/lib~这个路径，在遍历系统路径与用户路径后仍旧查无，最终抛出了UnsatisfiedLinkError

**Comment by Jucyfer** [comment]
> 继续深挖发现，在加载jctp.so时，ClassLoader的usr_paths并没有包含/tmp/lib~这个路径，在遍历系统路径与用户路径后仍旧查无，最终抛出了UnsatisfiedLinkError
不好意思，更正一下，在第二次NativeLibraryUtil.loadNativeLibrary(jniExtractor, libName,searchPaths)按绝对路径加载libjctp.so的时候，最终在java.lang.ClassLoader第2430行(native方法,load0)处报错。
两个libthost的so文件加载是正常的。

**Comment by Jucyfer** [comment]
@RationalityFrontline 将libjctp.so、两个libthost拷出来，复制到固定路径，并添加LD_LIBRARY_PATH之后，所有问题消失。
由此判断应该是从临时目录加载libjctp.so时发生未知错误导致程序无法继续执行。希望能修复一下，否则就跟这个项目的slogan相悖了。
